#include <stdio.h>
#include <rpc/rpc.h>        /* always needed */
#include "msg.h"            /* msg.h will be generated by rpcgen */

/*
 * Remote version of "printmessage"
 */

int * printmessage_1(char **msg, CLIENT *req)
{
    static int result;       /* must be static! */

    printf("%s\n", *msg);
    result = 1;
    return(&result);
}
